//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATN_QuanTri
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VATLIEULOTSANEntities : DbContext
    {
        public VATLIEULOTSANEntities()
            : base("name=VATLIEULOTSANEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CTPHIEUGIAO> CTPHIEUGIAOs { get; set; }
        public DbSet<PHIEUGIAO> PHIEUGIAOs { get; set; }
    }
}
