//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATN_QuanTri
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUGIAO
    {
        public PHIEUGIAO()
        {
            this.CTPHIEUGIAOs = new HashSet<CTPHIEUGIAO>();
        }
    
        public string MAPHIEUGIAO { get; set; }
        public string MAHD { get; set; }
        public Nullable<System.DateTime> NGAYGIAO { get; set; }
        public string DIACHIGIAO { get; set; }
        public string MANV { get; set; }
        public string SDTNV { get; set; }
        public string TINHTRANG { get; set; }
        public string NGUOINHAN { get; set; }
        public string SDTKH { get; set; }
    
        public virtual ICollection<CTPHIEUGIAO> CTPHIEUGIAOs { get; set; }
    }
}
